databases:
  - name: Hobbyists
    databaseName: Hobbyists
    user: Hobbyists

services:
  - type: web
    name: Hobbyists
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Hobbyists.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Hobbyists
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4