# Generated by Django 4.0.4 on 2022-05-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_preferences_delete_user_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='user',
        ),
    ]
