# Generated by Django 4.0.4 on 2023-04-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_choice_question_question_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
