# Generated by Django 4.0.4 on 2023-04-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='price_range',
        ),
        migrations.AddField(
            model_name='hobby',
            name='art',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='cost',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='craft',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='creative',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='focus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='intellectual',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='physicalexp',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='social',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='speed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='sport',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hobby',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
